# Site settings
title: "H.M.Yang's Blog"
description: "jekyll template demo."
keywords: ""
baseurl: ""
url: "http:////yhm07.github.io"
highlighter: pygments
paginate: 5
author:
    name: H.M.Yang
    github: YHM07
    email: hmyang07@gmail.com
    gitcafe: YHM07
    weibo: YHM07
qiniudn:                        # //{bucket}.qiniudn.com
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: rdiscount
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
# permalink: /:categories/:year-:month/:title.html

assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    provider: duoshuo
    duoshuo:
        name: YHM07                        # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串

# blogroll
blogroll: true
brlist:
    - text: "H.M.Yang's Space"
      url : //yhm07.github.io/
    - text: "StrayBirds"
      url: //yhm07.github.io/StrayBirds/
